(()=>{
'use strict';
const KEY='u39EmergencyProgressV4';
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const css=document.createElement('style');css.textContent=`#progBtn{position:fixed;right:14px;bottom:78px;z-index:90;border:1px solid #3d6272;background:#102733;color:#e9fbff;border-radius:999px;padding:10px 13px;font-weight:800}#progModal{display:none;position:fixed;inset:0;z-index:120;background:#000c;padding:16px;overflow:auto;color:#eef8fa;font:14px/1.5 system-ui}#progModal.open{display:block}.prgbox{max-width:680px;margin:5vh auto;background:#0b1b23;border:1px solid #385766;border-radius:18px;padding:18px}.prgrow{display:grid;grid-template-columns:170px 1fr 44px;gap:9px;align-items:center;margin:10px 0}.prgbar{height:10px;background:#02080b;border-radius:10px;overflow:hidden}.prgbar span{display:block;height:100%;background:#52d4df}.prgnote{padding:10px 12px;border-left:3px solid #e9b85b;background:#152027;margin:12px 0}.prgclose{border:1px solid #476777;background:#17303a;color:#eef8fa;border-radius:9px;padding:8px 11px;cursor:pointer}@media(max-width:600px){.prgrow{grid-template-columns:125px 1fr 40px}}`;document.head.appendChild(css);
const b=document.createElement('button');b.id='progBtn';b.textContent='Visão Programa';document.body.appendChild(b);const m=document.createElement('div');m.id='progModal';document.body.appendChild(m);
function data(){let p={runs:[]};try{p=JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){};const rs=(p.runs||[]).slice(-20).filter(r=>r.skills);if(!rs.length)return null;const avg=k=>Math.round(rs.reduce((a,r)=>a+(Number(r.skills[k])||0),0)/rs.length);return {n:rs.length,vals:[['Segurança',avg('seguranca')],['Estabilidade do Processo',avg('processo')],['Procedimento',Math.round((avg('diagnostico')+avg('priorizacao'))/2)],['Coordenação CIC–Campo',avg('coordenacao')]]}}
function render(){const d=data();m.innerHTML=`<div class="prgbox"><button class="prgclose" id="prgClose" style="float:right">Fechar</button><h2>Programa U-39 CIC · leitura comum</h2>${d?`<p>Leitura derivada das últimas <b>${d.n}</b> rodadas salvas.</p>${d.vals.map(v=>`<div class="prgrow"><span>${esc(v[0])}</span><div class="prgbar"><span style="width:${Math.max(0,Math.min(100,v[1]))}%"></span></div><b>${v[1]}</b></div>`).join('')}`:'<p>Ainda não há rodadas concluídas suficientes para montar a leitura integrada.</p>'}<div class="prgnote"><b>Importante:</b> esta visão não altera a avaliação V4. Segurança vem da competência Segurança; Estabilidade usa Processo; Procedimento é uma média didática de Diagnóstico + Priorização; Coordenação usa Coordenação. O relatório original e as barreiras críticas continuam soberanos dentro deste treinamento.</div></div>`;m.querySelector('#prgClose').onclick=()=>m.classList.remove('open')}
b.onclick=()=>{render();m.classList.add('open')};
})();
